#!/bin/bash

# read in project credentials config
filename=".credentials"

conf=""
dir="$PWD"
case "$dir" in
  "$HOME"*)
    while [[ ! -e "$dir/$filename" && "$dir" != "$HOME"  ]]; do
      dir=$(dirname "$dir")
    done
    ;;
esac
if [[ -e "$dir/$filename" ]]; then
  conf=$(cat "$dir/$filename")
fi

if [[ $conf == "" ]]; then
  DOCKER_BUILDKIT=1 docker build $@
  exit $?
fi

# convert 2 newlines to 1 tab
conf=${conf//$'\n'$'\n'/$'\t'}

# eat up further newlines
while [[ "$conf" =~ $'\t'$'\n' ]] ; do
  conf=${conf//$'\t'$'\n'/$'\t'}
done

# sqeeze tabs
conf=${conf//$'\t'$'\t'/$'\t'}

# split into array
IFS=$'\t'; result=( $conf )

secrets=""

# aggregate secrets
for credential in ${result[@]}; do
  mode=$(printf $credential | head -n 1)
  keys=$(printf $credential | sed 1d)
  credentials=""
  if [[ "$keys" == "" ]]; then
    credentials=$(credential-1password get --mode=$mode)
  else
    credentials=$(printf $keys | credential-1password get --mode=$mode)
  fi
  rc=$?
  if [[ "$rc" != "0" ]]; then
    exit $?
  fi
  secrets+="--secret=id=$mode-credentials,src=<(printf \$'$credentials') "
done

# build docker image with secrets
DOCKER_BUILDKIT=1 docker build $secrets $@
